# Generated by Django 4.1.3 on 2022-11-16 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeRecord',
        ),
    ]
