# Generated by Django 4.1.3 on 2022-11-16 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManager', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeerecord',
            old_name='image',
            new_name='picture',
        ),
    ]
