# Generated by Django 4.1.3 on 2022-11-17 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManager', '0005_remove_employeerecord_birthday_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeRecord',
        ),
    ]
